---
title: "The Red Sands Notes"
author: "Richard Lusch"
date: "February 17, 2017"
output: html_document
---

## Introduction

Must update & enter based off of previous notes.

Leader of previous party **Davis Lunthar**

### Characters



## Continuation

Messenger arrives for Magistrate *Tira Wirmwood*.  It's obvious she runs the town rather than delegating it.

**Chris** & **Tiffany** both roll and overhear what *Tira Wirmwood* has to say.

Sketstaf recieves summons at breakfast from Magistrate to hear sensitive message at her manor.  Will meet with rest of party.

Everyone rounded up and will attend except Drew the Druid.

*****

Magistrate's butler asks for weapons upon entry.  **Kat** and **Skestuf** give up weapons, rest hide them.

Well worn meeting room, with two new companions.

Magistrate wants to share information about other pilgrims who have been turned away from the mountains.  
"Reports are varied and inconsistent."
Reads, "Turned away by blinding panic, agressive animals, downed trees."
"Consistent, about old man sitting at bottom of mountain."
Witnesses may be in town.
Old, gray beard, old scar over right or left eye.  
"Big, fast lights"

**Bard** Confirms that there are bandits on the mountain, with confirmed reports about killing upon the mountain.  

Cleric has some idea of what is going on, based on something she may have read.

### First Encounter

Small smoking satchel flies in room and explodes in middle of room, making regular sighted people unable to see.

**Tira Attacked**  

Grandforge "Cover the Exits!", stumbles over a chair as he slams through the door they entered through attempting to regain his sword.

Tiefling shoots crossbow & misses.  Deftly leaps table to close distance.

**Chirs** "Healer to the magistrate!", attempts acrobatics over table in pursuit of assailant.

**Darkseers notice that butler is dead from arrows**

Bard tries shooting despite not being able to really see and misses everyone.  Tries to acrobatically get over table, stumles and slows him down.  (Does not get too far.)

**Chris** & **Tiff** get to see assailant.

Assailant runs down hall and leaps onto roof.

Grandforge tries running out the front to the back as he is unable to see the assailant.

**Kat** blows up 2 windows in attempt to make smoke dissipate.

**Cleric** finds out that magistrate is dead from dagger straight to the heart.  Also finds out that smoke is not poisonous.

**Chris** runs & flies out window to attack, and misses.  Now engaged in combat. Is in front of path of assailant.

**Bard** moves to window and uses bardsong to encourage group!

Assailant slips past **Chris**, whom unleashes fist barrage to assailants head, breaking his mask.

Grandforge see's jump, paces the assailant on the ground.  Notices guards approching, points to assialant "Stop that man!  He's injured the Magistrate!"

**Kat** begins to investigate in the room.  Examine arrows using local knowlege:  elven made, crafting was not military.  Find a small piece of paper tied to the arrow.

**Jenneca** Runs out of building yelling "Guards, guards"

**Tiffany** Grabs mask, leaps onto next building with little grace.  Assailant "Chuckles".  Babbles and rapier begins to crackle.

**Chris** flies and tries to grapple with assailant.  As he collides, he grips the assailant.

**Guard1** Considers shooting flying creature, but since he sees two creatures grappled and decides to get more guards.

**Bard** tries to climb to roof and falls into rosebush, but continues to sing his encouragine song.

**Guard2** Runs in separate direction as **Guard**

**Assailant** fails to break grapple.

**Grandforge** climbs 3/4 of building to reach assailant

**Katrina** tries to jump up roof, does not succeed, lands near bard.

**Cleric** begins casting spell, chanting rather angrily (compel hostility) and succeeds.  Assailant obviously wants to hurt the Cleric.

**Kat** attacks does 21 damage with one single hit.  **Assailant** Screams out in pain.

**Chris** Attempts to bash head into roof, while keeping jaw stable.

**Bard** Tries to figure out where **Assailant** was heading and succeeds wildly. 

Random not here.
